[package]
name = "translate-utils"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
encoding_rs.workspace = true
serde.workspace = true
serde_json.workspace = true
once_cell.workspace = true
serde_with = "3.15"
strum = { version = "0.27", features = ["derive"] }
